In [ ]:
#Structure: np.array(object,dtype)


# Indexing over numpy array

In [ ]:
# value ranges -3 to +3
import numpy as np
a = np.random.randn(4,4)
# to check signature of any method
a

array([[ 0.23848839,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
a[0] #returns 1st row

array([ 0.23848839,  0.72614082, -0.83215345,  0.34967982])

In [ ]:
# last row
a[-1]

array([-1.75304683, -0.66983669,  0.71168002,  1.00625846])

In [ ]:
# default indexing works on rows and it will return single row
# bt if i want multiple rows? then use slicing
a[:2] # will return 1st 2 rows

array([[ 0.23848839,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459]])

In [ ]:
a[::-1]# reverse rows

array([[-1.75304683, -0.66983669,  0.71168002,  1.00625846],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 0.23848839,  0.72614082, -0.83215345,  0.34967982]])

In [ ]:
# 1st and 3rd row
a[::2]

array([[ 0.23848839,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
# 2nd and 4th row
a[1::2]

array([[-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
# Assignmnt:
#- acess last 2 rows
#- access middle 2 rows
# - access 1st and last row
# access 2nd and last row
# access last 3 rows

In [ ]:
a[1]

array([-0.17822753, -0.69364757, -0.86893848, -0.34948459])

In [ ]:
a[1][1]

-0.6936475707646587

In [ ]:
a[-1][-1]

1.0062584605681644

In [ ]:
# Numpy array is Mutable
# replace 1st element by 0
#a[0,0]
a[0][0] = 0

In [ ]:
a

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

## work on columns

In [ ]:
#a[:] works on rows
a[:,:] # [row,column]

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
a[:,1:]#start reading from column with index 1

array([[ 0.72614082, -0.83215345,  0.34967982],
       [-0.69364757, -0.86893848, -0.34948459],
       [ 1.3197055 ,  2.19759204,  0.04234566],
       [-0.66983669,  0.71168002,  1.00625846]])

In [ ]:
a[:,::-1]

array([[ 0.34967982, -0.83215345,  0.72614082,  0.        ],
       [-0.34948459, -0.86893848, -0.69364757, -0.17822753],
       [ 0.04234566,  2.19759204,  1.3197055 ,  1.60202513],
       [ 1.00625846,  0.71168002, -0.66983669, -1.75304683]])

In [ ]:
a[:,1:3]

array([[ 0.72614082, -0.83215345],
       [-0.69364757, -0.86893848],
       [ 1.3197055 ,  2.19759204],
       [-0.66983669,  0.71168002]])

In [ ]:
# access single column
a[:,1]

array([ 0.72614082, -0.69364757,  1.3197055 , -0.66983669])

In [ ]:
a[:,-1]

array([ 0.34967982, -0.34948459,  0.04234566,  1.00625846])

In [ ]:
a[:][1:3]

array([[-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566]])

In [ ]:
a[:,1000:9] #slicing never gives an error it gives empty output

array([], shape=(4, 0), dtype=float64)

In [ ]:
a

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
# select 3rd number from column with index 1
a[2,1]

1.319705499806338

In [ ]:
a[2:3,1]

array([1.3197055])

In [ ]:
a

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
# Assignment:
#- access corner elements
# access diagonal elements
# access middle 2 columns and all rows
# access last 2 rows and its first 2 values from each row
# reverse rows and columns as well

In [ ]:
# to check structure of Numpy
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [ ]:
# check info of any method
np.unique?

In [ ]:
np.info(np.unique)

 unique(ar, return_index=False, return_inverse=False, return_counts=False,
        axis=None)

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
return_counts : bool, optional
    If True, also return the number 

## Shape Manipulation

In [ ]:
a

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
a.shape

(4, 4)

In [ ]:
a.ndim

2

In [ ]:
# np.ravel(): converts any dim array to 1D (temp.)
np.ravel(a)

array([ 0.        ,  0.72614082, -0.83215345,  0.34967982, -0.17822753,
       -0.69364757, -0.86893848, -0.34948459,  1.60202513,  1.3197055 ,
        2.19759204,  0.04234566, -1.75304683, -0.66983669,  0.71168002,
        1.00625846])

In [ ]:
a

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982],
       [-0.17822753, -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566],
       [-1.75304683, -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
#np.resize:it converts an array into any dimension: Parmenently
# in a we have 4x4 means 16 numbers
a.resize(16) # will conveert into 1D

In [ ]:
a

array([ 0.        ,  0.72614082, -0.83215345,  0.34967982, -0.17822753,
       -0.69364757, -0.86893848, -0.34948459,  1.60202513,  1.3197055 ,
        2.19759204,  0.04234566, -1.75304683, -0.66983669,  0.71168002,
        1.00625846])

In [ ]:
a.ndim

1

In [ ]:
# convert to 3D
a.resize(2,4,2)

In [ ]:
a

array([[[ 0.        ,  0.72614082],
        [-0.83215345,  0.34967982],
        [-0.17822753, -0.69364757],
        [-0.86893848, -0.34948459]],

       [[ 1.60202513,  1.3197055 ],
        [ 2.19759204,  0.04234566],
        [-1.75304683, -0.66983669],
        [ 0.71168002,  1.00625846]]])

In [ ]:
a.ndim

3

In [ ]:
# np.reshape: converts an array from any dim to any dim(temp.)
a.shape

(2, 4, 2)

In [ ]:
a.reshape(2,8)

array([[ 0.        ,  0.72614082, -0.83215345,  0.34967982, -0.17822753,
        -0.69364757, -0.86893848, -0.34948459],
       [ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566, -1.75304683,
        -0.66983669,  0.71168002,  1.00625846]])

In [ ]:
a.shape

(2, 4, 2)

In [ ]:
a.reshape(4,2,2)

array([[[ 0.        ,  0.72614082],
        [-0.83215345,  0.34967982]],

       [[-0.17822753, -0.69364757],
        [-0.86893848, -0.34948459]],

       [[ 1.60202513,  1.3197055 ],
        [ 2.19759204,  0.04234566]],

       [[-1.75304683, -0.66983669],
        [ 0.71168002,  1.00625846]]])

In [ ]:
a #so original array nt changed

array([[[ 0.        ,  0.72614082],
        [-0.83215345,  0.34967982],
        [-0.17822753, -0.69364757],
        [-0.86893848, -0.34948459]],

       [[ 1.60202513,  1.3197055 ],
        [ 2.19759204,  0.04234566],
        [-1.75304683, -0.66983669],
        [ 0.71168002,  1.00625846]]])

In [ ]:
a.reshape(2,1,8)

array([[[ 0.        ,  0.72614082, -0.83215345,  0.34967982,
         -0.17822753, -0.69364757, -0.86893848, -0.34948459]],

       [[ 1.60202513,  1.3197055 ,  2.19759204,  0.04234566,
         -1.75304683, -0.66983669,  0.71168002,  1.00625846]]])

In [ ]:
a.shape

(2, 4, 2)

In [ ]:
# Q. reshape(temp) vs resize(parmanent)

In [ ]:
# transpose: converting rows to columns and vice-versa
a

array([[[ 0.        ,  0.72614082],
        [-0.83215345,  0.34967982],
        [-0.17822753, -0.69364757],
        [-0.86893848, -0.34948459]],

       [[ 1.60202513,  1.3197055 ],
        [ 2.19759204,  0.04234566],
        [-1.75304683, -0.66983669],
        [ 0.71168002,  1.00625846]]])

In [ ]:
a.T

array([[[ 0.        ,  1.60202513],
        [-0.83215345,  2.19759204],
        [-0.17822753, -1.75304683],
        [-0.86893848,  0.71168002]],

       [[ 0.72614082,  1.3197055 ],
        [ 0.34967982,  0.04234566],
        [-0.69364757, -0.66983669],
        [-0.34948459,  1.00625846]]])

In [ ]:
b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
b.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [ ]:
np.transpose(b)

array([[1, 3],
       [2, 4],
       [3, 5]])