In [1]:
import numpy as np

In [50]:
arr = np.random.randn(4,4)
arr

array([[ 0.5474842 , -1.50995394,  0.80391851,  0.18185326],
       [ 2.19620673,  0.45342783, -1.65687394,  1.41690624],
       [-0.77857731, -0.82444922,  0.04737204, -0.48047794],
       [ 0.54506858, -1.14264443,  0.74603469, -1.65686173]])

### Assignmnt 1:
- acess last 2 rows
- access middle 2 rows
- access 1st and last row
- access 2nd and last row
- access last 3 rows

In [51]:
# access last 2 rows
arr[-2:]

array([[-0.77857731, -0.82444922,  0.04737204, -0.48047794],
       [ 0.54506858, -1.14264443,  0.74603469, -1.65686173]])

In [52]:
# access middle 2 rows
arr[1:-1]

array([[ 2.19620673,  0.45342783, -1.65687394,  1.41690624],
       [-0.77857731, -0.82444922,  0.04737204, -0.48047794]])

In [53]:
# access 1st and last rows
arr[0::3]

array([[ 0.5474842 , -1.50995394,  0.80391851,  0.18185326],
       [ 0.54506858, -1.14264443,  0.74603469, -1.65686173]])

In [55]:
# access 2nd and last row
arr[1::2]

array([[ 2.19620673,  0.45342783, -1.65687394,  1.41690624],
       [ 0.54506858, -1.14264443,  0.74603469, -1.65686173]])

### Assignment 2:
- access corner elements
- access diagonal elements
- access middle 2 columns and all rows
- access last 2 rows and its first 2 values from each row
- reverse rows and columns as well

In [57]:
# access corner elements
arr[0::3,0::3]

array([[ 0.5474842 ,  0.18185326],
       [ 0.54506858, -1.65686173]])

In [68]:
# access diagonal elements - pythonic way
[arr[i][i] for i in range(len(arr))]

[0.5474841982156186,
 0.4534278328507985,
 0.047372044028552274,
 -1.6568617340139888]

In [70]:
# access diagonal elements - numpy way
arr.diagonal()

array([ 0.5474842 ,  0.45342783,  0.04737204, -1.65686173])

In [74]:
# access middle 2 columns and all rows
arr[:,1:3]

array([[-1.50995394,  0.80391851],
       [ 0.45342783, -1.65687394],
       [-0.82444922,  0.04737204],
       [-1.14264443,  0.74603469]])

In [78]:
# access last 2 rows and its first 2 values from each row
arr[-2:,:2]

array([[-0.77857731, -0.82444922],
       [ 0.54506858, -1.14264443]])

In [79]:
#  reverse rows and columns as well
arr[::-1,::-1]

array([[-1.65686173,  0.74603469, -1.14264443,  0.54506858],
       [-0.48047794,  0.04737204, -0.82444922, -0.77857731],
       [ 1.41690624, -1.65687394,  0.45342783,  2.19620673],
       [ 0.18185326,  0.80391851, -1.50995394,  0.5474842 ]])