In [1]:
import numpy as np

In [2]:
# check numpy version
np.__version__

'1.23.5'

In [ ]:
#pip install numpy --upgrade
# python -m pip install numpy==x.y.z

# numpy.array(object,dtype)

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([3,4,5,6])

array([3, 4, 5, 6])

In [5]:
# change data type
np.array([3,4,5,6],dtype=float)

array([3., 4., 5., 6.])

In [6]:
# i want to create an array with all 0's
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros? # to check information

In [8]:
# NUMPY IS USED TO CREATE N DIMENSTIONAL ARRAYS
a = np.array([1,2,3])
#check dimension
a.ndim

1

In [9]:
a = np.array([[1,2,3],[5,6,7]])
#check dimension
a.ndim

2

In [10]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
a = np.array([[[1,2,3]],[[5,6,7]]])
#check dimension
a.ndim

3

In [12]:
a

array([[[1, 2, 3]],

       [[5, 6, 7]]])

In [13]:
# create 2D(rows,columns) array using zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# 3d(block,rows,columns) ARRAY
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
# Assignment: np.ones

In [15]:
# to create an array with constant value
#syntax: np.full(shape,fill_value)
np.full(4,900) # 900 4 times

array([900, 900, 900, 900])

In [18]:
# 2D
np.full((2,5),-1)

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [19]:
# to generate  the sequence of numbers use arange()
#syntax: np.arange(stop)
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(2,11,2) # 2-10 even numbers

array([ 2,  4,  6,  8, 10])

In [22]:
# addition of 1-100 odd numbers
sum(range(1,101,2))

2500

In [25]:
#sum(np.arange(1,101,2))
np.sum(np.arange(1,101,2))

2500

In [26]:
# create linearly spaced array
# Homogeneous spacing: difference between any 2 consecutive numbers is constant
#np.linspace(start,stop,num=50)
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [28]:
#5.7755102 - 5.95918367
9.44897959- 9.63265306

-0.18367347000000045

In [29]:
# if u want only 20 numbers
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [30]:
np.linspace(1,10,20,dtype=int)

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [31]:
# random number generation we use random from numpy
#random(size=None)
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random(5)

array([0.85515925, 0.40378063, 0.99087889, 0.60683394, 0.75922423])

In [ ]:
# how to recognize an array dimension
# [] 1D
# [[]] 2D
# [[[]]] 3D

In [36]:
# 2D random number array
np.random.random((3,3))

array([[0.63799943, 0.89439215, 0.31724293],
       [0.02151746, 0.3333527 , 0.07354082],
       [0.50173685, 0.05297329, 0.54789623]])

In [ ]:
# Assignment: Create a 3D array with random


In [38]:
# for random int generation
#randint(low, high=None, size=None, dtype=int)
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(2,7,10)

array([2, 6, 3, 3, 2, 2, 5, 2, 3, 6])

In [39]:
np.random.randint(18,60,100)

array([55, 37, 28, 22, 31, 30, 54, 25, 22, 44, 55, 49, 59, 31, 46, 43, 41,
       38, 35, 51, 26, 57, 26, 58, 50, 42, 50, 22, 38, 55, 53, 18, 30, 45,
       59, 27, 49, 31, 50, 51, 45, 43, 24, 45, 43, 47, 40, 43, 39, 48, 51,
       52, 52, 20, 50, 33, 43, 57, 37, 57, 46, 25, 22, 29, 21, 37, 48, 52,
       37, 30, 28, 48, 49, 43, 41, 22, 18, 34, 21, 20, 50, 53, 59, 19, 46,
       30, 25, 30, 44, 38, 19, 24, 58, 50, 56, 41, 35, 22, 31, 30])

In [40]:
# identity matrix: whose diagonal elements are 1 and non diagonal elements are 0
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# assignment: np.eye()