## Add -2 in each row (as last column)

In [12]:
import numpy as np
a=np.array(range(20)).reshape(4,5)
np.random.shuffle(a)
a


array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
newCol= np.array(range(4)) +21
newCol

array([21, 22, 23, 24])

In [27]:
newCol2d = np.array([newCol]).transpose()
newCol2d

array([[21],
       [22],
       [23],
       [24]])

In [28]:
np.append(a,newCol2d,axis=1)

array([[15, 16, 17, 18, 19, 21],
       [ 0,  1,  2,  3,  4, 22],
       [ 5,  6,  7,  8,  9, 23],
       [10, 11, 12, 13, 14, 24]])

## Addition of 2d arrays

In [33]:
arr1=np.array(range(20)).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
arr2=np.array(range(20,0,-1)).reshape(4,5)
arr2

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [41]:
# Sum of two matrices
arr1 + arr2

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [40]:
# Rowwise sum
arr1.sum(axis=1)

array([10, 35, 60, 85])

In [42]:
# Mean
arr1.mean()

9.5