In [ ]:
import numpy as np

# Inspecting the properties

In [ ]:
a = np.random.random((3,4))
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
# check rows and columns
a.shape #2D:(row,column)

(3, 4)

In [ ]:
# total elements in array
a.size

12

In [ ]:
len(a) # as a is 2D hence it returns no. of rows

3

In [ ]:
len(a.ravel())

12

In [ ]:
# check data type
a.dtype

dtype('float64')

In [ ]:
# check dimension
a.ndim

2

In [ ]:
# if array is already create and we want to change data type
# use astype(dtype)
a.astype(int) # temp

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# conver into str
a.astype(str)

array([['0.9950119110271972', '0.5834158354084847', '0.4264498451285985',
        '0.024531459951409484'],
       ['0.17168554693805138', '0.318340660227591', '0.8339150661099732',
        '0.8813111486416202'],
       ['0.489898158468845', '0.5954243742970804', '0.19719591677154136',
        '0.8464649026364188']], dtype='<U32')

In [ ]:
# COnvert an array to list
a.tolist()

[[0.9950119110271972,
  0.5834158354084847,
  0.4264498451285985,
  0.024531459951409484],
 [0.17168554693805138,
  0.318340660227591,
  0.8339150661099732,
  0.8813111486416202],
 [0.489898158468845,
  0.5954243742970804,
  0.19719591677154136,
  0.8464649026364188]]

In [ ]:
# convert numpy array to dict
dict(a)

ValueError: dictionary update sequence element #0 has length 4; 2 is required

In [ ]:
dict((enumerate(a)))

{0: array([0.99501191, 0.58341584, 0.42644985, 0.02453146]),
 1: array([0.17168555, 0.31834066, 0.83391507, 0.88131115]),
 2: array([0.48989816, 0.59542437, 0.19719592, 0.8464649 ])}

In [ ]:
# what is type of numpy array
type(a) #ndarray : n dimensional array

numpy.ndarray

## Operations over numpy array

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
np.max(a)

0.9950119110271972

In [ ]:
a.max()

0.9950119110271972

In [ ]:
# Rowwise max number: we have to give axis=1
a.max(axis=1)

array([0.99501191, 0.88131115, 0.8464649 ])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
# Columnwise max number: we have to give axis=0
a.max(axis=0)

array([0.99501191, 0.59542437, 0.83391507, 0.88131115])

In [ ]:
b = np.random.random((3,2,2))
b

array([[[0.49001779, 0.12615538],
        [0.00158663, 0.93509861]],

       [[0.1663223 , 0.89154994],
        [0.95085959, 0.78975766]],

       [[0.98244737, 0.73363984],
        [0.62640792, 0.17970284]]])

In [ ]:
b.max()

0.9824473678294152

In [ ]:
b.max(axis=1)

array([[0.49001779, 0.93509861],
       [0.95085959, 0.89154994],
       [0.98244737, 0.73363984]])

In [ ]:
b[1]

array([[0.1663223 , 0.89154994],
       [0.95085959, 0.78975766]])

In [ ]:
b[1].max(axis=1)

array([0.89154994, 0.95085959])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
a + 100

array([[100.99501191, 100.58341584, 100.42644985, 100.02453146],
       [100.17168555, 100.31834066, 100.83391507, 100.88131115],
       [100.48989816, 100.59542437, 100.19719592, 100.8464649 ]])

In [ ]:
np.add(a,100)

array([[100.99501191, 100.58341584, 100.42644985, 100.02453146],
       [100.17168555, 100.31834066, 100.83391507, 100.88131115],
       [100.48989816, 100.59542437, 100.19719592, 100.8464649 ]])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
x =  np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
x+=10
x

array([11, 12, 13, 14])

In [ ]:
# use list now
y = [1,2,3,4]
y +=10
y

TypeError: 'int' object is not iterable

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
np.add(a,100)

array([[100.99501191, 100.58341584, 100.42644985, 100.02453146],
       [100.17168555, 100.31834066, 100.83391507, 100.88131115],
       [100.48989816, 100.59542437, 100.19719592, 100.8464649 ]])

In [ ]:
np.append(a,100)

array([9.95011911e-01, 5.83415835e-01, 4.26449845e-01, 2.45314600e-02,
       1.71685547e-01, 3.18340660e-01, 8.33915066e-01, 8.81311149e-01,
       4.89898158e-01, 5.95424374e-01, 1.97195917e-01, 8.46464903e-01,
       1.00000000e+02])

In [ ]:
np.append(x,100) # add element at the end

array([ 11,  12,  13,  14, 100])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
# add -1 in each column
# add -1 row
np.append(a,[[-1,-1,-1,-1]],axis=0)

array([[ 0.99501191,  0.58341584,  0.42644985,  0.02453146],
       [ 0.17168555,  0.31834066,  0.83391507,  0.88131115],
       [ 0.48989816,  0.59542437,  0.19719592,  0.8464649 ],
       [-1.        , -1.        , -1.        , -1.        ]])

In [ ]:
# Assignment: Add -2 in each row

In [ ]:
# delete(arr,index)
np.delete(a,0)

array([0.58341584, 0.42644985, 0.02453146, 0.17168555, 0.31834066,
       0.83391507, 0.88131115, 0.48989816, 0.59542437, 0.19719592,
       0.8464649 ])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
np.delete(a,1,axis=0) # deleting middle row

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

In [ ]:
np.delete(a,-1,axis=1) # delete last column

array([[0.99501191, 0.58341584, 0.42644985],
       [0.17168555, 0.31834066, 0.83391507],
       [0.48989816, 0.59542437, 0.19719592]])

In [ ]:
a

array([[0.99501191, 0.58341584, 0.42644985, 0.02453146],
       [0.17168555, 0.31834066, 0.83391507, 0.88131115],
       [0.48989816, 0.59542437, 0.19719592, 0.8464649 ]])

## Selection over numpy array

In [ ]:
z = np.random.randint(1,11,20).reshape(4,5)
z

array([[ 5,  4,  8,  8, 10],
       [ 1,  5,  8, 10,  8],
       [ 1,  2,  6,  7,  4],
       [ 6,  7,  2,  3,  7]])

In [ ]:
np.random.randint(1,11,20).reshape(4,5)

array([[ 5, 10,  4,  9,  6],
       [ 4,  8,  8,  1,  9],
       [ 3,  3,  7,  7,  6],
       [ 4,  9,  8,  6, 10]])

In [ ]:
z

array([[ 5,  4,  8,  8, 10],
       [ 1,  5,  8, 10,  8],
       [ 1,  2,  6,  7,  4],
       [ 6,  7,  2,  3,  7]])

In [ ]:
# select numbers > 5
z > 5  #mapping is element by element

array([[False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True, False],
       [ True,  True, False, False,  True]])

In [ ]:
# numpy array supports boolean indexing
z[z>5] # this will return actual value for whome result is True

array([ 8,  8, 10,  8, 10,  8,  6,  7,  6,  7,  7])

In [ ]:
# convert num >5 to 0
z[z>5] = 0

In [ ]:
z

array([[5, 4, 0, 0, 0],
       [1, 5, 0, 0, 0],
       [1, 2, 0, 0, 4],
       [0, 0, 2, 3, 0]])